const text_en = {
    authorizationPage: {
      bannerText: "It's easier to help animals together with FreeVet!",
    },
    authOptions: {
      register: "Register",
      or: "or",
      login: "Log in",
    },
    registrationPage: {
      header: "Create a new account",
      addPhoto: "Add photo",
      nameLabel: "Name",
      placeholderName: "Your name",
      nameErrorRequired: "Name is required",
      nameErrorMinLength: "Minimum 2 characters",
      phoneLabel: "Phone",
      phoneErrorRequired: "Phone is required",
      phoneErrorPattern: "Please enter a valid phone number",
      submitButton: "Send code",
      privacyPolicyText: "By clicking the Send code button, you agree to the<br></br>Privacy Policy",
    },
    phoneLoginPage: {
      header: "Login by phone number",
      subtitle: "Please enter the phone number you registered with,<br></br>",
      lostAccess: "Lost access to your phone?",
      accessRestoration: "Contact us to restore access",
      submitButton: "Send code",
    },
    burgerMenu: {
      editProfile: "Edit profile",
      settings: "Settings",
    },
    codeInputBox: {
      codeLabel: "Code",
      requiredError: "You entered an incorrect code! Please try again",
      resendText: "Did not receive the code?",
      resendButton: "Resend code",
      resendWait: "You can request the code again in {{seconds}} seconds",
    },
    customButton: {
      submitText: "Submit",
      disabledText: "Unavailable",
    },
    customButtonSubmit: {
      submitText: "Submit",
      disabledText: "Unavailable",
    },
    customCheckbox: {
      checkedTooltip: "Checkbox is checked",
      uncheckedTooltip: "Checkbox is unchecked",
    },
    customInput: {
      defaultErrorMessage: "Please fill out this field",
    },
    customMessage: {
      questionTitle: "Question No.",
      awaitingResponse: "Awaiting response",
      homelessAnimal: "Homeless animal",
    },
    customPetCard: {
      statusMessage: 'Status:',
    },
    customStickTitle: {
      userText: "User",
    },
    fileUploader: {
      uploadLimitError: "You can upload up to {{maxFiles}} files.",
      unsupportedFileType: "File {{fileName}} has an unsupported type.",
    },
    footer: {
      main: "Home",
      profile: "Profile",
      donate: "Support",
      service: "About the service",
    },
    userRolePage: {
      header: "Participant Status",
      role: "Choose your role in the service",
      helpWithFreeVet: "Who do you plan to help with FreeVet?",
      helpHomelessAnimals: "Homeless animals",
      helpPets: "Pets",
      tellAboutYourself: "Tell us about yourself",
      volunteer: "I am a volunteer",
      shelterWorker: "I am a shelter worker",
      havePet: "I have a pet",
      userStick: "User",
      or: "or",
      wantToJoin: "Do you want to become a member of the FreeVet team?",
      vetDoctor: "I am a veterinarian",
      cynologist: "I am a cynologist",
      zooPsychologist: "I am a zoo psychologist",
      vetStick: "Specialist",
      saveBtn: "Save",
    },
    l_createVetBookPage: {
      header: "Veterinary Book",
      noBook: "It seems that your pet<br></br>doesn't have a digital veterinary book yet :(",
      petName: "Pet's Name",
      namePlaceholder: "Enter the pet's name",
      addPhoto: "Add a photo",
      petArt: "Type of animal",
      petWeight: "Approximate weight of the animal",
      petGender: "Gender of the animal",
      vetBook_description: "The veterinary book is a digital version of the pet's passport<br></br>with useful features,<br></br>simplifying the care process.",
      noCreateBtn: "Do not create",
      createBtn: "Create",
    },

    form: {
      createAccount: "Create an account",
      name: "Name",
      phone: "Phone",
      namePlaceholder: "Enter your name",
      phonePlaceholder: "Enter your phone number",
      addPhoto: "Add photo",
      selectRole: "Choose your role",
      helpWithFreeVet: "Help with FreeVet",
      helpHomelessAnimals: "Help homeless animals",
      helpPets: "Help pets",
      tellAboutYourself: "Tell us about yourself",
      volunteer: "Volunteer",
      shelterWorker: "Shelter worker",
      havePet: "I have a pet",
      or: "or",
      wantToJoin: "Do you want to join us?",
      vetDoctor: "Veterinarian",
      cynologist: "Cynologist",
      zooPsychologist: "Zoo psychologist",
      phoneLogin: "Phone login is not yet implemented",
    },
    formHeader: {
      backButtonAlt: "Back",
      title: "Create a new account",
    },
    questionPage: {
      title: "Ask a question",
      animalSelection: "Select the animal you want to ask about,<br />",
      newAnimal: "Animals<br />without digital veterinary books",
      addAnimal: "New animal",
      continueButton: "Continue",
    },
    closeQuestionPage: {
      header: "Close question",
      confirmation: "Are you sure you want to close the question?",
      ratingPrompt: "Please rate the veterinarian's responses <br /> on a scale from 1 to 10, <br /> where 1 - not at all liked, <br /> 10 - everything was great! &#42",
      feedbackPrompt: "You can leave your feedback",
      submitButton: "Close question",
    },
    descriptionAnimalPage: {
      title: "Ask a question",
      addMedia: "Add photo and/or video",
      petArt: "Type of animal",
      petWeight: "Approximate weight of the animal",
      petGender: "Gender of the animal",
      homelessCheckbox: "Animal is homeless",
      continueButton: "Continue",
      requiredSymbol: "*",
      validationMessages: {
        petArt: {
          required: "Type of animal is required",
          minLength: "Minimum 2 characters",
        },
        petWeight: {
          required: "Weight of the animal is required",
          minLength: "Minimum 2 characters",
        },
        petGender: {
          required: "Gender of the animal is required",
          minLength: "Minimum 2 characters",
        },
      },
    },
 sendQuestionPage: {
      header: "Ask a question",
      addedMedia: "Added photos and/or videos",
      noPhotos: "No photos available",
      petArt: "Type of animal",
      petWeight: "Approximate weight of the animal",
      petGender: "Gender of the animal",
      homeless: "Animal is homeless: ",
      questionPlaceholder: "Enter your question",
      submitButton: "Submit question",
      requiredField: "Field is required",
    },
    mainHeader: {
      title: "Welcome to FreeVet",
      description: "A service of the TailBook ecosystem that allows you to ask qualified and experienced veterinarians questions for free and receive answers.",
    },
    verificationPage: {
      header: "Phone Verification",
      enterCode: "Please enter the code you received<br></br>on the specified phone",
      confirm: "Confirm",
    },
    vetVerificationPage: {
      header: "Verification",
      notAuthorized: "It seems you are not authorized<br></br>in the service as a specialist :(",
      additionalData: "Please provide additional data,<br></br>for your authorization as a specialist",
      nameLabel: "Full Name",
      nameRequired: "Name is required",
      nameMinLength: "Minimum two characters",
      documentsLabel: "Please add documents,<br></br>confirming your qualifications",
      additionalInfoLabel: "You can also provide additional information",
      emailLabel: "Email",
      emailRequired: "Email is required",
      emailPattern: "Invalid email format",
      telegramLabel: "Telegram",
      telegramRequired: "Telegram is required",
      telegramMinLength: "Minimum five characters",
      specializationLabel: "Specify your specialization",
      specializationRequired: "Specialization is required",
      specializationMinLength: "Minimum five characters",
      petArtLabel: "Specify the animals (cats, dogs, etc.)<br></br>that you specialize in",
      petArtRequired: "Field is required",
      petArtMinLength: "Minimum five characters",
      dataReliability: "I confirm the accuracy of the provided information",
      submitBtn: "Submit",
      cancelBtn: "Cancel",
    },
    vetCodePage: {
      header: "Verification",
      notAuthorized: "It seems you are not authorized<br></br>in the service as a specialist :(",
      enterCode: "Please enter the code you received<br></br>for authorization",
      cancel: "Cancel",
      submit: "Submit",
    },
    opportunity: {
      title: "Opportunities",
      askQuestion: "Ask a question",
      clinicNavigator: "Veterinary Clinic Navigator",
      pharmacyNavigator: "Veterinary Pharmacy Navigator",
      veterinaryBooks: "Veterinary Books",
      onlineReception: "Online Consultation",
      more: "And much more",
      inDevelopment: "in development",
    },
    questionPetList: {
      title: "Animals<br></br>with digital veterinary books",
    },
    statistics: {
      title: "Assistance Statistics",
      helpedAnimals: "assistance provided to animals",
      helpedThisMonth: "animals helped this month",
      donatedAmount: "euros donated for project development",
      thankYou: "Thank you for your support!",
    },
    accordion: {
      title: "Additional Description",
      breedlabel: "Breed",
      breedplaceholder: "Mixed long-haired",
      colorlabel: "Color",
      colorplaceholder: "Ginger",
      agelabel: "Date of Birth",
      ageplaceholder: "01.10.2023",
      features: "Special Features",
      featuresplaceholder: "Polydactyl",
      chipNumberLabel: "Chip Number",
      chipNumberPlaceholder: "11110120202010210202330340435040540",
      clinicLabel: "Clinic where the chip was implanted",
      clinicPlaceholder: "MontVet Podgorica",
      chipLocationLabel: "Location of the chip implant",
      chipLocationPlaceholder: "Withers",
      rabiesVaccination: "Rabies Vaccination",
      vaccineLabel: "Vaccine*",
      vaccinePlaceholder: "Nobivac",
      seriesLabel: "Series*",
      seriesPlaceholder: "0989",
      expiryDateLabel: "Expiry Date*",
      expiryDatePlaceholder: "01.01.2025",
      clinicVaccineLabel: "Clinic where the vaccine was given*",
      clinicVaccinePlaceholder: "MontVet Podgorica",
      vaccineDateLabel: "Vaccination Date*",
      vaccineDatePlaceholder: "10.01.2024",
      validityEndDateLabel: "Validity End Date*",
      validityEndDatePlaceholder: "10.01.2025",
      weightlabel: "Weight",
      weightplaceholder: "Enter weight",
      statuslabel: "Status",
      statusplaceholder: "Enter status",
      identification: "Identification",
      otherVaccinations: "Other vaccinations",
      deworming: "Deworming",
      dewormingDrugLabel: "Dewormer*",
      dewormingDrugPlaceholder: "Nobivac",
      dewormingDateLabel: "Deworming Date*",
      dewormingDatePlaceholder: "10.01.2024",
      clinicDewormingLabel: "Clinic where deworming was performed (or self-performed)",
      clinicDewormingPlaceholder: "MontVet Podgorica",
      ectoparasiteTreatment: "Ectoparasite treatment",
      clinicalExamination: "Clinical examination",
      examinationDateLabel: "Date*",
      examinationDatePlaceholder: "10.01.2024",
      resultLabel: "Result",
      resultPlaceholder: "Healthy, certificate issued",
      registration: "Registration",
      registrationClinicLabel: "Clinic",
      registrationClinicPlaceholder: "MontVet Podgorica",
      registrationNumberLabel: "Registration Number",
      registrationNumberPlaceholder: "1212039483984837583",
      files: "Files",
      chipDateLabel: "Chip Implant Date",
      chipDatePlaceholder: "10.01.2021",
      phototitle: "Add photo",
      photofileLabel: "Attach file",
      photolimitMessage: "Upload up to {{maxFiles}} files.",
      photounsupportedMessage: "File {{fileName}} has an unsupported type.",
    },
    inputPlaceholders: {
      breed_placeholder: "Mixed long-haired",
      color_placeholder: "Ginger",
      age_placeholder: "Enter age",
      weight_placeholder: "Enter weight",
      status_placeholder: "Enter status",
    },
    userPage: {
      userName: "Andrei Yeremin",
      userRoleVolunteer: "I am a volunteer",
      userRolePetOwner: "I have a pet",
      myQuestions: "My questions",
      allQuestions: "all",
      animalInfo: "Street cat etc...",
      vetBooks: "Veterinary books",
      allVetBooks: "all",
      myAnimalsTitle: "My animals",
      strayAnimalsTitle: "Stray animals",
    },
  };
  
  export default text_en;
  