const texts = {
  authorizationPage: {
    bannerText: "Помогать животным проще вместе с FreeVet!+++",
  },
  authOptions: {
    register: "Зарегистрироваться+++",
    or: "или+++",
    login: "Войти+++",
  },
  registrationPage: {
      header: "Создать новый аккаунт+++",
      addPhoto: "Добавить фото+++",
      nameLabel: "Имя+++",
      nameErrorRequired: "Имя обязательно+++",
      nameErrorMinLength: "Минимум 2 символа+++",
      phoneLabel: "Телефон+++",
      phoneErrorRequired: "Телефон обязателен+++",
      phoneErrorPattern: "Введите корректный номер телефона+++",
      submitButton: "Отправить код+++",
      privacyPolicyText: "Нажимая на кнопку Отправить код, Вы соглашаетесь с Политикой конфиденциальности+++",
  },
  burgerMenu: {
    editProfile: "Редактировать профиль+++",
    settings: "Настройки+++",
  },
  codeInputBox: {
    codeLabel: "Код+++",
    requiredError: "Вы ввели неправильный код! Попробуйте еще раз+++",
    resendText: "Не пришел код?+++",
    resendButton: "Отправить код повторно+++",
    resendWait: "Запросить код повторно можно через {{seconds}} секунд+++",
  },
  customButton: {
      submitText: "Отправить+++", 
      disabledText: "Недоступно+++", 
  },
  customButtonSubmit: {
      submitText: "Отправить+++", 
      disabledText: "Недоступно+++", 
  },
  customCheckbox: {
      checkedTooltip: "Чекбокс отмечен+++",  
      uncheckedTooltip: "Чекбокс не отмечен+++", 
  },
  customInput: {
      defaultErrorMessage: "Пожалуйста, заполните это поле+++", 
  },
  customMessage: {
      questionTitle: "Вопрос №+++", 
      awaitingResponse: "Ожидает ответа+++", 
      homelessAnimal: "Бездомное животное+++", 
  },
  customPetCard: {
      statusMessage: 'Статус:+++', 
  },
  customStickTitle: {
      userText: "Пользователь+++",  
  },
  fileUploader: {
      uploadLimitError: "Вы можете загрузить до {{maxFiles}} файлов.+++",
      unsupportedFileType: "Файл {{fileName}} имеет неподдерживаемый тип.+++",
  },
  footer: {
      main: "Главная+++",
      profile: "Профиль+++",
      donate: "Поддержать+++",
      service: "О сервисе+++",
  },
  form: {
      createAccount: "Создать аккаунт+++",
      name: "Имя+++",
      phone: "Телефон+++",
      namePlaceholder: "Введите ваше имя+++",
      phonePlaceholder: "++++",
      addPhoto: "Добавить фото+++",
      selectRole: "Выберите вашу роль+++",
      helpWithFreeVet: "Помогите с бесплатным ветеринаром+++",
      helpHomelessAnimals: "Помогите бездомным животным+++",
      helpPets: "Помогите домашним животным+++",
      tellAboutYourself: "Расскажите о себе+++",
      volunteer: "Волонтер+++",
      shelterWorker: "Работник приюта+++",
      havePet: "У меня есть питомец+++",
      or: "или+++",
      wantToJoin: "Хотите присоединиться к нам?+++",
      vetDoctor: "Ветеринар+++",
      cynologist: "Кинолог+++",
      zooPsychologist: "Зоопсихолог+++",
      phoneLogin: "Вход по телефону еще не реализован+++",
  },
  formHeader: {
      backButtonAlt: "Назад+++", 
       title: "Создать новый аккаунт", 
  },
  questionPage: {
      header: "Задать вопрос+++", 
      animalSelection: "Выберите животное,<br />по которому хотите задать вопрос+++",
      newAnimal: "Животные<br />без цифровых ветеринарных книжек+++",
      continueButton: "Продолжить+++", 
  },
  closeQuestionPage: {
      header: "Закрыть вопрос+++", 
      confirmation: "Вы уверены, что хотите закрыть вопрос?+++",
      ratingPrompt: "Пожалуйста, оцените ответы ветеринарного врача <br /> по шкале от 1 до 10, <br /> где 1 - совсем не понравилось, <br /> 10 - все супер! &#42+++",
      feedbackPrompt: "Вы можете оставить свой отзыв+++",
      submitButton: "Закрыть вопрос+++", 
  },
  descriptionAnimalPage: {
      title: "Задать вопрос+++",
      addMedia: "Добавьте фото и (или) видео+++",
      petArt: "Вид животного+++",
      petWeight: "Примерный вес животного+++",
      petGender: "Пол животного+++",
      homelessCheckbox: "Животное является бездомным+++",
      continueButton: "Продолжить+++",
      requiredSymbol: "*+++",
      validationMessages: {
          petArt: {
              required: "Вид животного обязательно+++",
              minLength: "Минимум 2 символа+++",
          },
          petWeight: {
              required: "Вес животного обязательно+++",
              minLength: "Минимум 2 символа+++",
          },
          petGender: {
              required: "Пол животного обязательно+++",
              minLength: "Минимум 2 символа+++",
          },
      },
  },
  sendQuestionPage: {
      header: "Задать вопрос+++",
      addedMedia: "Добавленные фото и (или) видео+++",
      noPhotos: "Фото отсутствует+++",
      petArt: "Вид животного+++",
      petWeight: "Примерный вес животного+++",
      petGender: "Пол животного+++",
      homeless: "Животное бездомное: +++",
      questionPlaceholder: "Введите текст+++", 
      submitButton: "Отправить вопрос+++", 
      requiredField: "Поле обязательно для заполнения+++",
  },
  mainHeader: {
      title: "Добро пожаловать в FreeVet+++",
      description: "Сервис экосистемы TailBook, предоставляющий возможность бесплатно задавать вопросы квалифицированным опытным ветеринарным врачам и получать ответы на них.+++"
  },
  verificationPage: {
    header: "Проверка телефона", 
    enterCode: "Пожалуйста введите полученный Вами <br /> на указанный телефон код", 
    confirm: "Подтвердить", 
  },
  opportunity: {
      title: "Возможности+++",
      askQuestion: "Задать вопрос+++",
      clinicNavigator: "Навигатор ветклиник+++",
      pharmacyNavigator: "Навигатор ветаптек+++",
      veterinaryBooks: "Ветеринарные книжки+++",
      onlineReception: "Онлайн-прием+++",
      more: "И многое другое+++",
      inDevelopment: "в разработке+++",
  },
  questionPetList: {
      title: "Животные+++",
      subtitle: "с цифровыми ветеринарными книжками+++",
  },
  statistics: {
      title: "Статистика помощи+++",
      helpedAnimals: "животным оказана помощь+++",
      helpedThisMonth: "животным помогли в этом месяце+++",
      donatedAmount: "евро пожертвовано на развитие проекта+++",
      thankYou: "Спасибо за Вашу поддержку!+++",
  },
  accordion: {
      additionalDescription: {
        title: "Дополнительное описание+++",
        breed: { label: "Порода+++", placeholder: "Беспородный длинношерстный+++" },
        color: { label: "Окрас+++", placeholder: "Рыжий+++" },
        age: { label: "Возраст+++", placeholder: "Введите возраст+++" },
        weight: { label: "Вес+++", placeholder: "Введите вес+++" },
        status: { label: "Статус+++", placeholder: "Введите статус+++" },
        identification: "Идентификация+++",
        rabiesVaccination: "Вакцинация от бешенства+++",
        otherVaccinations: "Другие вакцинации+++",
        deworming: "Дегельминтизация+++",
        ectoparasiteTreatment: "Лечение эктопаразитов+++",
        clinicalExamination: "Клиническое обследование+++",
        registration: "Регистрация+++",
        files: "Файлы+++",
      },
      photo: {
        title: "Добавить фото+++",
        fileLabel: "Прикрепите файл+++", 
        limitMessage: "Загрузите до {{maxFiles}} файлов.+++", 
        unsupportedMessage: "Файл {{fileName}} имеет неподдерживаемый тип.+++",
      },
  },
  inputPlaceholders: {
    breed_placeholder: "Беспородный длинношерстный+++", 
    color_placeholder: "Рыжий+++", 
    age_placeholder: "Введите возраст+++", 
    weight_placeholder: "Введите вес+++", 
    status_placeholder: "Введите статус+++", 
  },
};

export default texts;
